// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Replace these placeholder values by running:
/// dart run flutterfire_cli:flutterfire configure
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform. '
          'Run "dart run flutterfire_cli:flutterfire configure" to generate options.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDoRg0x25w9Oghn3lO914Tk3r7mgUdCaU',
    appId: '1:479218484040:android:ba1e8c4f1783de65e2e97d',
    messagingSenderId: '479218484040',
    projectId: 'anon-cast',
    storageBucket: 'anon-cast.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'anon-cast',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.anonCast',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBe3GVz9C7pnPFUNR-lSFe2Vka4LvDD0Ag",
      authDomain: "anon-cast.firebaseapp.com",
      projectId: "anon-cast",
      storageBucket: "anon-cast.firebasestorage.app",
      messagingSenderId: "479218484040",
      appId: "1:479218484040:web:96c6f26713722a5fe2e97d",
      measurementId: "G-QT9VEJS06R");
}
